homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.story3, name='story3'),
    path('profile/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def story3(request):
    return render(request, 'story3.html')

def portfolio(request):
	return render(request, 'portfolio.html')

def contact(request):
	return render(request, 'contact.html')

homepage/templates/contact.html
{% extends 'navbar.html' %}
{% load static %}
{% block content %}

          <title>c o n t a c t | z a h r a</title>

            <div class="container mt-5 ml-1">
                <h1 id= "judulbayangan"; >
                        contact
                    </h1>
                <h1 id= "judul";>
                    contact
                </h1>
            </div>
        
            <div class="container ">
              <div class="row  ml-5">
                <div class="col socialmedia">
                  <a href="https://www.linkedin.com/in/azzahraabraara/"><i class="fa fa-linkedin fa-rotate-270" style="font-size:28px;color:#576566;max-width: 28px; margin: 10px 10px;"></i></a>
                  <br>
                  <a href="https://open.spotify.com/user/zahraabr?si=B1YdNcu7Ss-nQrdBEEPmTw"><i class="fa fa-spotify fa-rotate-270" style="font-size:28px;color:#576566;max-width: 28px; margin: 10px 10px;"></i></a>
                  <br>
                  <a href="https://www.instagram.com/zahrabrr"><i class="fa fa-instagram fa-rotate-270" style="font-size:28px;color:#576566;max-width: 28px; margin: 10px 10px;"></i></a>
                  <br>
                  <a href="https://www.twitter.com/zahraabr"><i class="fa fa-twitter fa-rotate-270" style="font-size:28px;color:#576566;max-width: 28px; margin: 10px 10px;"></i></a>
              </div>
                <div class="col-sm-4 text-center">
                  <img src = "{% static 'phone.png' %}" style="width:100px">
                  <br><br><br>
                  <img src = "{% static 'mail.png' %}" style="width:100px">
                </div>
                <div class="col-sm-1 text-center">
                  <div id= "square">
                  </div>
                </div>
                <div class="col-sm-5 contact">
                  <p>0812 1965 0683
                    <br><br><br>
                    zahraabraara@gmail.com
                  </p>
                </div>
              </div>
            </div>

            <div class="container">
              <br>
              <br>
              <br>
              <br>
              <br>
            </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
        {% endblock %}

homepage/templates/footer.html
<footer>
    <div style="text-align: center;font-family: Arial, Helvetica, sans-serif;">
      <h5>© 2020 Copyright Azzahra Abraara</h5>
    </div>
</footer>

homepage/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style3.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-transparent fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'homepage:story3' %}#welcome"><img src="{% static 'zahra logo.png' %}" style="max-width: 60px;"></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link js-scroll-trigger navbarfont" href="{% url 'homepage:story3' %}#welcome">HOME <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle navbarfont" href="#about" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        ABOUT
                        </a>
                        <div class="dropdown-menu navbarfont" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item navbarfont" href="{% url 'homepage:story3' %}#aboutsaya">GET TO KNOW ME</a>
                            <a class="dropdown-item navbarfont" href="{% url 'homepage:story3' %}#skill">SKILL</a>
                            <a class="dropdown-item navbarfont" href="{% url 'homepage:story3' %}#education">EDUCATION</a>
                            <a class="dropdown-item navbarfont" href="{% url 'homepage:story3' %}#experience">EXPERIENCE</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger navbarfont" href= "{% url 'homepage:portfolio' %}">PORTFOLIO</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger navbarfont" href="{% url 'homepage:contact' %}">CONTACT</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

{% block content %}

{% endblock %}
{% include 'footer.html' %}

</body>
</html>

homepage/templates/portfolio.html
{% extends 'navbar.html' %}
{% load static %}
{% block content %}

        <title>p o r t f o l i o | z a h r a</title>

        <div class="container mt-5 ml-1">
            <h1 id= "judulbayangan"; >
                    portfolio
                </h1>
            <h1 id= "judul";>
                 portfolio
            </h1>
        </div>
        
        <div class="container">
          <div class="row">
            <div class="col socialmedia">
                <a href="https://www.linkedin.com/in/azzahraabraara/"><i class="fa fa-linkedin fa-rotate-270" style="font-size:28px;color:#576566;max-width: 28px; margin: 10px 10px;"></i></a>
                <br>
                <a href="https://open.spotify.com/user/zahraabr?si=B1YdNcu7Ss-nQrdBEEPmTw"><i class="fa fa-spotify fa-rotate-270" style="font-size:28px;color:#576566;max-width: 28px; margin: 10px 10px;"></i></a>
                <br>
                <a href="https://www.instagram.com/zahrabrr"><i class="fa fa-instagram fa-rotate-270" style="font-size:28px;color:#576566;max-width: 28px; margin: 10px 10px;"></i></a>
                <br>
                <a href="https://www.twitter.com/zahraabr"><i class="fa fa-twitter fa-rotate-270" style="font-size:28px;color:#576566;max-width: 28px; margin: 10px 10px;"></i></a>
            </div>
            <div class="col-sm-4 ml-5">
                <div class="namaacara">
                open house fasilkom <br>ui
                </div>
                <p class="tahun">
                  2019
                </p>
            </div>
            <div class="col-sm ml-5">
              <img src = "{% static '1day.png' %}" style="width:250px">
            </div>
            <div class="col-sm ml-5">
              
              <img src = "{% static 'kenapa harus daftar oh.png' %}" style="width:250px"> 
            </div>
          </div>
        </div>

        <div class="container">
          <br><br><br>
        </div>

        <div class="container">
          <div class="row">
            <div class="col-sm">
              <img src = "{% static 'mia.png' %}" style="width:250px">
            </div>
            <div class="col-sm">
              
              <img src = "{% static 'open tenant.png' %}" style="width:250px">
            </div>
            <div class="col-sm">
              <div class="namaacara2">
                ui art war
              </div>
              <p class="tahun">
                2019
              </p>
            </div>
          </div>
        </div>
        
        <div class="container">
          <br><br><br>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-sm">
              <div class="namaacara3">
                pesta rakyat<br>komputer
              </div>
              <p class="tahun">
                2020
              </p>
            </div>
            <div class="col-sm">
              <img src = "{% static 'galeri.png' %}" style="width:250px">
            </div>
            <div class="col-sm">
              <img src = "{% static 'tangan.png' %}" style="width:250px">
            </div>
          </div>
        </div>
        
        <div class="container">
          <br><br>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
        {% endblock %}

homepage/templates/story3.html
{% extends 'navbar.html' %}
{% load static %}
{% block content %}

        <title>z a h r a</title>

        <div class="container mt-5 ml-1">
            <h1 id="judulbayangan">welcome</h1>
            <h1 id="welcome">welcome</h1>
        </div>

        <div class="container">
            <div class="row">
                <div class="col socialmedia">
                    <a href="https://www.linkedin.com/in/azzahraabraara/"><i class="fa fa-linkedin fa-rotate-270" style="font-size:28px;color:#576566;max-width: 28px; margin: 10px 10px;"></i></a>
                    <br>
                    <a href="https://open.spotify.com/user/zahraabr?si=B1YdNcu7Ss-nQrdBEEPmTw"><i class="fa fa-spotify fa-rotate-270" style="font-size:28px;color:#576566;max-width: 28px; margin: 10px 10px;"></i></a>
                    <br>
                    <a href="https://www.instagram.com/zahrabrr"><i class="fa fa-instagram fa-rotate-270" style="font-size:28px;color:#576566;max-width: 28px; margin: 10px 10px;"></i></a>
                    <br>
                    <a href="https://www.twitter.com/zahraabr"><i class="fa fa-twitter fa-rotate-270" style="font-size:28px;color:#576566;max-width: 28px; margin: 10px 10px;"></i></a>
                </div>
                <div class="col-sm">
                    <img class="float-right" src="{% static 'pantone.PNG' %}" style="width: 300px;">
                </div>
                <div class="col-sm">
                    <h2 id="tulisannama">Azzahra Abraara</h2>
                    <div class="row">
                        <div class="col-sm"><div id="circle1"></div></div>
                        <div class="col-sm"><div id="circle2"></div></div>
                        <div class="col-sm"><div id="circle3"></div></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container ml-1 mt-5">
            <h2 id="shadow">about me</h2>
            <h2 id="aboutsaya" name="aboutsaya">about me</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-sm">
                    <img src="{% static 'muke.png' %}" style="width: 300px;">
                </div>
                <div class="col-sm-8">
                    <h2>
                        <p class="paragrafnya">hello! i’m Azzahra Abraara. You can call me zahra. I was born on February 6th, 2001. 
                            Currently i’m studying Computer Science at University of Indonesia as a second year student. 
                            I like to watch series and movies especially mystery genre. 
                            Beside that, i am interested in stuffs like UI/UX design and i really love to sleep. That’s all i can say!</p>
                     </h2>
                </div>
            </div>
            
        </div>

        <div class="container mt-5">
            <h1 id="skill">skill</h1>
        </div>
    
        <div class="container">
            <div class="row">
                <div class="col-sm text-center">
                    <i class="fa fa-html5" style="font-size:128px;color:#5C2828;"></i>
                </div>
                <div class="col-sm text-center">
                    <img src = "{% static 'premier.png' %}" style="width:100px;">
                </div>
                <div class="col-sm text-center">
                    <img src = "{% static 'illustrator.png' %}" style="width:100px;">
                </div>
                <div class="col-sm text-center">
                    <img src = "{% static 'photoshop.png' %}" style="width:100px;">
                </div>

            </div>
        </div>

        <div class="container mt-5">
            <h1 id="education">education</h1>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-sm text-center">
                    <img src = "{% static 'school.png' %}" style="width:125px;"> <br><br>
                      <img src = "{% static 'university.png' %}" style="width:125px;">
                </div>
                
                <div class="col-sm" style= "color: #5C2828;font-size: 20px">
                        <p>
                            <br>
                            Jakarta Islamic school<br>
                            2007 - 2018
                            <br><br><br>
                            Universitas Indonesia<br>
                            Faculty of Computer Science<br>
                            2018 - present
                        </p>
                </div>
            </div>
        </div>

        <div class="container mt-5">
            <h1 id="experience">
                experience
            </h1>
        </div>
        
        <div class="container">
            <center><img src="{% static 'experience.JPG' %}" id="experiencenya"></center>
        </div>

        <div class="container">
            <br>
        </div>  

                            <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
            CILUUKKKK??????????????
        </button>
        
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">you are wasting your time</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                BAAAAAA!!!!!!!!!!!!!
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
            </div>
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

{% endblock %}